### ISSUE TITLE
Don't gather print statements (or similar) by default

### ISSUE THREAD

**Issue by greazer** [microsoft/python-program-analysis#6]
This issue's repro is related to issue #5. 

Given this script/notebook:

```
#%%
import pandas as pd # pandas is a dataframe library

#%%
Cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Price': [22000,25000,27000,35000]
        }
df = pd.DataFrame(Cars,columns= ['Brand', 'Price'])

#%%
def check(df, size=11):
    print(df)

#%%
check(df)

#%%
print(df)

#%%
x = df['Brand'].values
y = df['Price'].values

```

***Expected***
```
# This file contains the minimal amount of code required to produce the code cell you gathered.
#%%
import pandas as pd # pandas is a dataframe library

#%%
Cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Price': [22000,25000,27000,35000]
        }
df = pd.DataFrame(Cars,columns= ['Brand', 'Price'])

#%%
def check(df, size=11):
    print(df)

#%%
check(df)

#%%
x = df['Brand'].values
y = df['Price'].values

```
No need to gather the stand-alone ```print(df)``` call (cell 5). Actually, I would expect the function "check" and it's call to not be there either, but that's the topic of issue #5. I'd think print calls should not be gathered by default. 

***Actual***
```
# This file contains the minimal amount of code required to produce the code cell you gathered.
#%%
import pandas as pd # pandas is a dataframe library

#%%
Cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Price': [22000,25000,27000,35000]
        }
df = pd.DataFrame(Cars,columns= ['Brand', 'Price'])

#%%
def check(df, size=11):
    print(df)

#%%
check(df)

#%%
print(df) ***Why is this gathered?***

#%%
x = df['Brand'].values
y = df['Price'].values

```

**Comment by rdeline** [comment]
Sigh. No repro. I added two unit tests to capture your scenario, [here](https://github.com/microsoft/python-program-analysis/blob/f2d7501e2e5db77e2df12113e4c8246d2ae8bc3e/src/test/log-slicer.test.ts#L11) and [here](https://github.com/microsoft/python-program-analysis/blob/f2d7501e2e5db77e2df12113e4c8246d2ae8bc3e/src/test/slice.test.ts#L174). Both tests pass. The tests ensure that the slice does not contain the call to print, the call to check, or the definition of check.

I'll follow up with you to understand your context more.

**Comment by greazer** [comment]
I'm not able to repro either. I'm not sure what was happening on my machine. I may have not been running with the latest npm module without realizing it as I had a bunch of weird build issues I had to work through with the python extension.
