### ISSUE TITLE
rewriteCellMagic is over aggressive

### ISSUE THREAD

**Issue by greazer** [microsoft/python-program-analysis#7]
The regex being used to match and comment out lines that contain cell magics is too aggressive. I think this one will do what's expected.

/^[^#\s]*\s*%%/gm

I actually created a PR but I can't submit because I'm not a contributor. :)

Because of this issue, any cell that contains code lines that have any %%'s in it will be entirely commented out. This is a problem if the user has a line in the cell like "# this is not a cell magic %%" or (in my case) "# To add a new cell, type '#%%'"

**Comment by rdeline** [comment]
The power to PR should now be yours. 😃

**Comment by rdeline** [comment]
Thanks for the PR! I added a test to show it works.
